"""Solving deprecated warnings for default values and enum

Revision ID: 472ce823e69c
Revises: ea8f30c9cfd6
Create Date: 2026-05-11 14:43:28.877998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472ce823e69c'
down_revision: Union[str, Sequence[str], None] = 'ea8f30c9cfd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
