"""Default timestamp changes"

Revision ID: ea8f30c9cfd6
Revises: 636757cbf182
Create Date: 2026-05-05 13:14:06.721153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8f30c9cfd6'
down_revision: Union[str, Sequence[str], None] = '636757cbf182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'status',
               existing_type=postgresql.ENUM('available', 'occupied', 'reserved', name='tablestatusenum'),
               type_=sa.Enum('available', 'occupied', 'reserved', name='table_status_enum'),
               postgresql_using='status::text::table_status_enum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'status',
               existing_type=sa.Enum('available', 'occupied', 'reserved', name='table_status_enum'),
               type_=postgresql.ENUM('available', 'occupied', 'reserved', name='tablestatusenum'),
               postgresql_using='status::text::tablestatusenum',
               existing_nullable=False)
    # ### end Alembic commands ###
